import PDFDocument from 'pdfkit';
import type { ColumnDefinition } from './export.types';
import type {
  TaskMetrics,
  UserProductivity,
  TeamWorkload,
  ProjectSummary,
  VelocityReport,
} from '../reports.types';

const COLORS = {
  primary: '#1E40AF',
  headerBg: '#EFF6FF',
  border: '#D1D5DB',
  textDark: '#111827',
  textMuted: '#6B7280',
  altRowBg: '#F9FAFB',
} as const;

const PAGE_MARGIN = 50;
const ROW_HEIGHT = 25;

interface PDFTableOptions {
  title: string;
  subtitle?: string;
  tenantName?: string;
  generatedAt: Date;
}

/**
 * Generate a styled PDF from tabular data.
 * Returns a Buffer containing the complete PDF.
 */
export async function generatePDF<T extends Record<string, unknown>>(
  data: T[],
  columns: ColumnDefinition[],
  options: PDFTableOptions
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: 'A4',
      layout: columns.length > 5 ? 'landscape' : 'portrait',
      margin: PAGE_MARGIN,
      info: {
        Title: options.title,
        Author: 'TaskSaaS',
        CreationDate: options.generatedAt,
      },
    });

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawHeader(doc, options);
    drawTable(doc, data, columns);

    const pageRange = doc.bufferedPageRange();
    for (let i = 0; i < pageRange.count; i++) {
      doc.switchToPage(i);
      drawFooter(doc, i + 1, pageRange.count, options.generatedAt);
    }

    doc.end();
  });
}

function drawHeader(doc: PDFKit.PDFDocument, options: PDFTableOptions): void {
  doc
    .fontSize(18)
    .fillColor(COLORS.primary)
    .text(options.title, PAGE_MARGIN, PAGE_MARGIN);

  if (options.subtitle) {
    doc
      .fontSize(10)
      .fillColor(COLORS.textMuted)
      .text(options.subtitle, PAGE_MARGIN, doc.y + 4);
  }

  if (options.tenantName) {
    doc
      .fontSize(9)
      .fillColor(COLORS.textMuted)
      .text(`Organization: ${options.tenantName}`, PAGE_MARGIN, doc.y + 2);
  }

  doc.moveDown(1.5);
}

function drawTable<T extends Record<string, unknown>>(
  doc: PDFKit.PDFDocument,
  data: T[],
  columns: ColumnDefinition[]
): void {
  const pageWidth = doc.page.width - 2 * PAGE_MARGIN;
  const columnWidth = pageWidth / columns.length;
  let y = doc.y;

  // Table header row
  doc.rect(PAGE_MARGIN, y, pageWidth, ROW_HEIGHT).fill(COLORS.headerBg);

  columns.forEach((col, i) => {
    doc
      .fontSize(9)
      .fillColor(COLORS.primary)
      .text(col.header, PAGE_MARGIN + i * columnWidth + 4, y + 7, {
        width: columnWidth - 8,
        ellipsis: true,
      });
  });

  y += ROW_HEIGHT;

  // Data rows
  for (let rowIdx = 0; rowIdx < data.length; rowIdx++) {
    const row = data[rowIdx];

    // Check if we need a new page
    if (y + ROW_HEIGHT > doc.page.height - PAGE_MARGIN - 30) {
      doc.addPage();
      y = PAGE_MARGIN;
    }

    // Alternate row background
    if (rowIdx % 2 === 1) {
      doc.rect(PAGE_MARGIN, y, pageWidth, ROW_HEIGHT).fill(COLORS.altRowBg);
    }

    columns.forEach((col, i) => {
      const value = row[col.key];
      const formatted = col.formatter ? col.formatter(value) : String(value ?? '');

      doc
        .fontSize(8)
        .fillColor(COLORS.textDark)
        .text(formatted, PAGE_MARGIN + i * columnWidth + 4, y + 7, {
          width: columnWidth - 8,
          ellipsis: true,
        });
    });

    y += ROW_HEIGHT;
  }

  // Bottom border
  doc
    .moveTo(PAGE_MARGIN, y)
    .lineTo(PAGE_MARGIN + pageWidth, y)
    .strokeColor(COLORS.border)
    .stroke();
}

function drawFooter(
  doc: PDFKit.PDFDocument,
  pageNumber: number,
  totalPages: number,
  generatedAt: Date
): void {
  const bottom = doc.page.height - 30;

  doc
    .fontSize(7)
    .fillColor(COLORS.textMuted)
    .text(
      `Generated by TaskSaaS on ${generatedAt.toISOString().split('T')[0]}`,
      PAGE_MARGIN,
      bottom
    )
    .text(`Page ${pageNumber} of ${totalPages}`, PAGE_MARGIN, bottom, {
      align: 'right',
      width: doc.page.width - 2 * PAGE_MARGIN,
    });
}

// --- Report-specific PDF generators ---

export async function exportTaskMetricsPDF(metrics: TaskMetrics): Promise<Buffer> {
  const rows: Record<string, unknown>[] = [
    {
      Category: 'Summary',
      Name: 'Total Tasks',
      Count: metrics.totalTasks,
      Percentage: '100.0%',
    },
    {
      Category: 'Summary',
      Name: 'Completed',
      Count: metrics.completedTasks,
      Percentage:
        metrics.totalTasks > 0
          ? `${((metrics.completedTasks / metrics.totalTasks) * 100).toFixed(1)}%`
          : '0.0%',
    },
    {
      Category: 'Summary',
      Name: 'Overdue',
      Count: metrics.overdueCount,
      Percentage:
        metrics.totalTasks > 0
          ? `${((metrics.overdueCount / metrics.totalTasks) * 100).toFixed(1)}%`
          : '0.0%',
    },
    ...metrics.statusDistribution.map((s) => ({
      Category: 'Status',
      Name: s.name,
      Count: s.count,
      Percentage:
        metrics.totalTasks > 0
          ? `${((s.count / metrics.totalTasks) * 100).toFixed(1)}%`
          : '0.0%',
    })),
    ...metrics.priorityDistribution.map((p) => ({
      Category: 'Priority',
      Name: p.priority,
      Count: p.count,
      Percentage:
        metrics.totalTasks > 0
          ? `${((p.count / metrics.totalTasks) * 100).toFixed(1)}%`
          : '0.0%',
    })),
  ];

  const columns: ColumnDefinition[] = [
    { key: 'Category', header: 'Category' },
    { key: 'Name', header: 'Metric' },
    { key: 'Count', header: 'Count' },
    { key: 'Percentage', header: 'Percentage' },
  ];

  return generatePDF(rows, columns, {
    title: 'Task Metrics Report',
    generatedAt: new Date(),
  });
}

export async function exportUserProductivityPDF(
  data: UserProductivity[]
): Promise<Buffer> {
  const columns: ColumnDefinition[] = [
    { key: 'userName', header: 'User' },
    { key: 'userEmail', header: 'Email' },
    { key: 'totalTasks', header: 'Total' },
    { key: 'completedTasks', header: 'Completed' },
    { key: 'overdueTasks', header: 'Overdue' },
    {
      key: 'onTimePercentage',
      header: 'On-Time %',
      formatter: (v) => `${Number(v).toFixed(1)}%`,
    },
  ];

  return generatePDF(data as unknown as Record<string, unknown>[], columns, {
    title: 'User Productivity Report',
    generatedAt: new Date(),
  });
}

export async function exportTeamWorkloadPDF(
  data: TeamWorkload[]
): Promise<Buffer> {
  const columns: ColumnDefinition[] = [
    { key: 'userName', header: 'Member' },
    { key: 'totalTasks', header: 'Tasks' },
    { key: 'urgent', header: 'Urgent' },
    { key: 'highPriority', header: 'High' },
    { key: 'overdue', header: 'Overdue' },
    {
      key: 'workloadScore',
      header: 'Score',
      formatter: (v) => Number(v).toFixed(1),
    },
  ];

  return generatePDF(data as unknown as Record<string, unknown>[], columns, {
    title: 'Team Workload Report',
    generatedAt: new Date(),
  });
}

export async function exportProjectSummaryPDF(
  data: ProjectSummary[]
): Promise<Buffer> {
  const columns: ColumnDefinition[] = [
    { key: 'projectName', header: 'Project' },
    { key: 'totalTasks', header: 'Total' },
    { key: 'completedTasks', header: 'Done' },
    { key: 'overdueTasks', header: 'Overdue' },
    {
      key: 'completionRate',
      header: 'Rate',
      formatter: (v) => `${Number(v).toFixed(1)}%`,
    },
  ];

  return generatePDF(data as unknown as Record<string, unknown>[], columns, {
    title: 'Project Summary Report',
    generatedAt: new Date(),
  });
}

export async function exportVelocityPDF(
  report: VelocityReport
): Promise<Buffer> {
  const columns: ColumnDefinition[] = [
    { key: 'date', header: 'Period' },
    { key: 'created', header: 'Created' },
    { key: 'completed', header: 'Completed' },
  ];

  return generatePDF(report.data as unknown as Record<string, unknown>[], columns, {
    title: 'Velocity Report',
    subtitle: `Period: ${report.period} | Avg velocity: ${report.averageVelocity}`,
    generatedAt: new Date(),
  });
}
